package display;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;


import net.miginfocom.swing.MigLayout;
import users.CurrentUser;
import users.GuestProfile;
import users.UserProfile;
import users.UsernameExistsException;
import users.UsernameNotFoundException;
import users.Users;
import users.WrongPasswordException;
/**
 * The following was auto-generated by Window Builder Pro.
 * This class defines the login window graphical interface
 * for the pacman game. The login window contains a username
 * and password field as well as a choice of options to login,
 * play as a guest, create a new user or exit the game.
 * 
 * @author Carl Patenaude Poulin
 * @author Antoine Tu
 */
public class LoginWindow {

	private JFrame frame;
	private JTextField usernameField;
	private JPasswordField passwordField;
	
	/**
	 * Create the login window.
	 */
	public LoginWindow() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 380, 170);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(new MigLayout("", "[][][][][][][][][][][grow][][][][][][][][][][][][][][grow]", "[][][][][][]"));
		
		JLabel lblPacman = new JLabel("Pac-Man");
		frame.getContentPane().add(lblPacman, "cell 3 0 10 1,alignx center");
		
		final JLabel errorMessageLabel = new JLabel("");
		errorMessageLabel.setHorizontalAlignment(SwingConstants.CENTER);
		frame.getContentPane().add(errorMessageLabel, "cell 3 1 4 1");
		
		JLabel lblUsername = new JLabel("Username");
		frame.getContentPane().add(lblUsername, "cell 3 2,alignx right");
		
		usernameField = new JTextField();
		frame.getContentPane().add(usernameField, "cell 4 2 3 1,growx");
		usernameField.setColumns(10);
		
		JLabel lblPassword = new JLabel("Password");
		frame.getContentPane().add(lblPassword, "cell 3 3,alignx right");
		
		passwordField = new JPasswordField();
		frame.getContentPane().add(passwordField, "cell 4 3 3 1,growx");
		
		JButton btnLogin = new JButton("Log-in");
		btnLogin.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				try {
					CurrentUser.setInstance(Users.getInstance().getUser(usernameField.getText(), new String(passwordField.getPassword())));
					WindowManager.openMainMenu();
				} catch(UsernameNotFoundException e) {
					errorMessageLabel.setText("Error: The username you have specified was not found.");
				} catch(WrongPasswordException e) {
					errorMessageLabel.setText("Error: You have entered the wrong password.");
				}
			}
		});
		
		frame.getContentPane().add(btnLogin, "cell 3 4,growx");
		
		JButton btnGuestUser = new JButton("Guest User");
		btnGuestUser.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				CurrentUser.setInstance(new GuestProfile());
				WindowManager.openMainMenu();
			}
		});
		
		frame.getContentPane().add(btnGuestUser, "cell 4 4");
		
		JButton btnNewUser = new JButton("New User");
		btnNewUser.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				try {
					UserProfile user = null;
					try {
						user = Users.getInstance().addUser(usernameField.getText(), new String(passwordField.getPassword()));
					} catch (IOException e) {
						e.printStackTrace();
					}
					CurrentUser.setInstance(user);
					WindowManager.openMainMenu();
				} catch(UsernameExistsException e) {
					errorMessageLabel.setText("Error: The user already exists");
				}
			}
		});
		frame.getContentPane().add(btnNewUser, "cell 5 4");
		
		JButton btnExit = new JButton("Exit");
		btnExit.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				System.exit(0);
			}
		});
		frame.getContentPane().add(btnExit, "cell 6 4,growx");
		frame.setVisible(true);
	}
	
	/**
	 * Dispose of the login window.
	 */
	public void dispose() {
		frame.dispose();
	}
}
